### ISSUE TITLE
Support export as PDF

### ISSUE THREAD

**Issue by wayne3602** [verocloud/obsidian-mindmap-nextgen#129]
Hello, i love this plugin, it makes my notes more clear. Thanks for your development!

Currently, i write a note to conclude my textbook, it has so mach content so i write a lot of outlines, i can see clear structure by your plugin, but when i want to export it to save and share it to my friends, it looks like pretty vague when i enlarge it. 

eg.
![H8HR3~Z}DGF(KB @04L ``C](https://user-images.githubusercontent.com/88063517/219051921-a302df23-02e5-4c76-98b0-9c2cf1133812.png)

Hence, i wish you support it export as PDF, i think it will be more clear when i enlarge it.

Thanks!

**Comment by AdrianSimionov** [comment]
@james-tindal what about HiDpi PNG? Might be quicker to implement.

Is the screenshot a d3 to png process or a screenshot of the screen? Maybe the zoom was not set right?

**Comment by james-tindal** [comment]
Yeah, it's using d3SvgToPng, set to { scale: 3 }.
I'll look more into in a minute.

**Comment by james-tindal** [comment]
It always output the same size image, regardless of the size of the mindmap

**Comment by james-tindal** [comment]
d3SvgToPng basically just takes a screenshot, so the width:height ratio is always the same as the tab the mindmap is in. Could potentially fix that in future with a different library. @AdrianSimionov

**Comment by james-tindal** [comment]
@wayne3602 This should be fixed if you install the latest version.

**Comment by wayne3602** [comment]
@james-tindal Thanks! It looks clear now.

**Comment by AdrianSimionov** [comment]
Fixed by increasing the resolution of the exported PNG.

I have no interest not in export to PDF.

**Comment by quancs** [comment]
@AdrianSimionov Exporting document containing `markmap` to pdf makes the obsidian stuck, and the exported PDF doesnot have the `markmap`. Will you fix it? ^_^
