### ISSUE TITLE
Obsidian is freezing after activation of the "obsidian-mindmap-nexgen" Plugin.

### ISSUE THREAD

**Issue by Titanfinger** [verocloud/obsidian-mindmap-nextgen#136]
# When i install this Plugin in Obsidian under MacOSX 10.15.7 (Catalina)
- I cant click anywhere in Obsidian.
- I needed to deactivate the Plugin to solve the Issue.
- How can i investigate what happend?
  
- Or have some others the same Problem like me?
  
Thanks for your efforts.

**Comment by james-tindal** [comment]
Hi @Titanfinger. Could you try the following to get more information for me?
Press cmd+alt+i.
Click on the Console tab
<img width="365" alt="image" src="https://user-images.githubusercontent.com/10291002/219970779-2d36bdb9-e279-444d-aae5-1c52fdb65048.png">
Send me a screenshot of whatever messages are in there,

**Comment by james-tindal** [comment]
Are you using the latest version of Obsidian. You can check in the "About" tab in the Preferences window

**Comment by zcysxy** [comment]
Same here. After installing the plugin, related commands do not show in the command palette. Then after a reboot, Obsidian freezes. I need to remove the plugin folder and reboot Obsidian.

**Comment by james-tindal** [comment]
Would be very helpful if you could get me the same information I asked for above please, @zcysxy

**Comment by zcysxy** [comment]
> Same here. After installing the plugin, related commands do not show in the command palette. Then after a reboot, Obsidian freezes. I need to remove the plugin folder and reboot Obsidian.

Hi @james-tindal, for the first problem, disabling the old mindmap plugin solves it.
<img width="627" alt="image" src="https://user-images.githubusercontent.com/48207708/219976169-64808779-d0d5-4454-97da-f9468e07e985.png">

However, Obsidian still freezes after a reboot if `obsidian-mindmap-nextgen` exists in the plugin folder, and I cannot get the error info. My Obsidian version is 1.1.14.

**Comment by zcysxy** [comment]
Strangely, with the same plugin set (I copied the `plugins` folder), the sandbox vault does not have this issue. Logs in the sandbox vault:
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/48207708/219977016-18218df3-0c58-44e0-b132-f4122b4d2e64.png">

**Comment by james-tindal** [comment]
Thanks. Could you click <img width="389" alt="image" src="https://user-images.githubusercontent.com/10291002/219977352-eb419348-0423-465b-8bb1-4606e14afe7d.png"> and show me what comes up?

**Comment by james-tindal** [comment]
Never mind. I see the line number.

**Comment by zcysxy** [comment]
I found the issue may be a conflict with the Kanban plugin. I was able to create a minimal working example:

1. In the sandbox vault, install and enable this plugin and Kanban plugin
2. Create a Kanban Markdown with the following content
3. Reboot Obsidian and open the Kanban note, then Obsidian will freeze

```markdown
---

kanban-plugin: basic

---

## hello

- [ ] Something
- [ ] Something else

## world

- [ ] hello
- [ ] this
- [ ] something
- [ ] [[Start Here]]


%% kanban:settings
```
{"kanban-plugin":"basic"}
```
%%
```

**Comment by james-tindal** [comment]
On my side, Obsidian crashes when I try to paste your example into the document. With no error, and the text never gets pasted.

**Comment by zcysxy** [comment]
> On my side, Obsidian crashes when I try to paste your example into the document. With no error, and the text never gets pasted.

Yes, same for me. Super weird. If you write the file with another editor, it crashes when you open it.

**Comment by zcysxy** [comment]
Sorry for the misleading information above. I located the real problem: wikilink after a checkbox, typing the following line will freeze Obsidian

```markdown
- [ ] [[some note]]
```

**Comment by james-tindal** [comment]
Great. Minimal reproducible example. I've noticed it's unrelated to the Kanban plugin.

**Comment by james-tindal** [comment]
Pushed the fix to production. @zcysxy @Titanfinger Check the latest version please guys.

**Comment by woshitoutouge** [comment]
This morning I find OB freeze once I open a specific file, it took me 2 hours to test the problem, I have no choice but to enable/disable every plugin that i installed, finally i find this new mindmap plugin, the problem solved after i disable or update this  plugin. such a relief

**Comment by zcysxy** [comment]
Issue solved, thanks @james-tindal !

**Comment by james-tindal** [comment]
Bad times, @woshitoutouge 
Glad you figured it out!
