### ISSUE TITLE
Plugin messes with yaml across all files since the last plugin update

### ISSUE THREAD

**Issue by MSBack** [verocloud/obsidian-mindmap-nextgen#146]
It seems that the plugin is adding "null" to empty yaml entries and reformatting them as multi-line rather than single line arrays. I have concluded this because after enabling the plugin, this behavior begins, when otherwise it is not there.

**Comment by james-tindal** [comment]
Are you sure this wasn't happening before the latest version?

**Comment by james-tindal** [comment]
Rest assured this will not cause data loss.

**Comment by MSBack** [comment]
It seems to have just started since this update. Can you explain why this behavior is part of the plugin? Is it intentional or not?

**Comment by james-tindal** [comment]
It's unintentional. I used a function to read the frontmatter, and didn't realise it was reformatting it.
However, I am planning on implementing a feature that will update the frontmatter upon user request, but not at random times like this. Don't know yet if I'll be able to avoid this reformatting.
