### ISSUE TITLE
Markmap images

### ISSUE THREAD

**Issue by redscorpse** [verocloud/obsidian-mindmap-nextgen#153]
I can't see images on the mindmap view. I can use images with MarkMap on VSCode, and also with (older obsidian plugins)[https://github.com/lynchjames/obsidian-mind-map], but I don't know why it isn't working with yours :( Could you fix that, please? (I'm using the obsidian IOS app, I don't know if it works on other devices)

**Comment by AdrianSimionov** [comment]
Someone needs to check on Desktop OS if this works, or is an iOS bug.

**Comment by ToppDev** [comment]
Seems to work on Linux
![image](https://user-images.githubusercontent.com/17766093/229113420-3ee7cb14-8657-4d6d-9cb3-9121f0c2c512.png)

Image added with
```
![](https://github.githubassets.com/images/icons/emoji/unicode/1f970.png)
```

**Comment by redscorpse** [comment]
Thanks for checking, it may be a problem with the app or with my document then...

**Comment by james-tindal** [comment]
fixed
