### ISSUE TITLE
Number of nodes limit: Nodes cannot continue nesting after six levels of nesting

### ISSUE THREAD

**Issue by zhraa11** [verocloud/obsidian-mindmap-nextgen#166]
Number of nodes limit: Nodes cannot continue nesting after six levels of nesting
<img width="203" alt="image" src="https://user-images.githubusercontent.com/98087300/232322292-635ef819-b7f8-4e20-94e4-b94504a890a5.png">

**Comment by james-tindal** [comment]
This is part of the Markdown specification. What you've shown is Obsidian's enforcement of the spec. Regarding the mindmap, that's handled [Markmap](https://github.com/markmap/markmap). I think it's unlikely we're going to try to work around that in the plugin.

You can nest lists to arbitrary depth.
https://www.markdownguide.org/basic-syntax/#unordered-lists
