### ISSUE TITLE
Mindmap not working on Obsidian Version 1.5.8 (Installer 1.4.13)

### ISSUE THREAD

**Issue by coolgoose85** [verocloud/obsidian-mindmap-nextgen#197]
I installed the plugin and then copy pasted markup codeblock as mentioned but it does not convert it into mindmap.

Is there anything else I need to do which im missing here? Attaching screenshot.
![2024-02-24_21-19-56](https://github.com/verocloud/obsidian-mindmap-nextgen/assets/5456587/a48b3c9b-2958-4abd-9ca0-d6622dad4325)

**Comment by james-tindal** [comment]
What happens when you open a mindmap tab?

**Comment by coolgoose85** [comment]
>What happens when you open a mindmap tab?
How do i open the mindmap tab?

Also i created new doc and corrected the mistake still don't see anything
![2024-02-25_10-44-26](https://github.com/verocloud/obsidian-mindmap-nextgen/assets/5456587/3b249d68-3816-46de-ac4a-c77abd8c4f96)
![2024-02-25_10-44-46](https://github.com/verocloud/obsidian-mindmap-nextgen/assets/5456587/914a215e-90c7-4ec2-8653-f9ed38009e5f)

**Comment by james-tindal** [comment]
It's probably conflicting with any of the other mind map plugins you have installed. Turn them off, then see if it works.

**Comment by coolgoose85** [comment]
Is there anyway to enable debug logs to diagnose the issue?

**Comment by james-tindal** [comment]
cmd-shift-i on mac. ctrl-shift-i on windows.
