### ISSUE TITLE
Font selection toggle option

### ISSUE THREAD

**Issue by AdrianSimionov** [verocloud/obsidian-mindmap-nextgen#30]
Font when rendering not aligned with the font of the current theme.

Add a toggle option in settings and a true/false option in frontmatter to either use the default font or use the font of the current theme.

**Comment by MasterTuto** [comment]
This one is a little complex, I have tried many approaches, but there are no native (in terms of using the markmap library itself) and it breaks in case the font is larger than the default. The font toggle itself is pretty easy, but it breaks easily and should be re rendered considering the new font size and etc. There are no possible default adjusts, as the new font can be of any size, width, height or anything like that.

So I will just  hang up this one for now.

**Comment by james-tindal** [comment]
https://github.com/markmap/markmap/discussions/152#discussioncomment-4869670

**Comment by james-tindal** [comment]
The only way I can see this causing a problem is if the code changes the font _after_ markmap is done rendering. As long as the font is decided before render, markmap renders based on the size of the text contained in each node.
