### ISSUE TITLE
Add rendered code background color option

### ISSUE THREAD

**Issue by AdrianSimionov** [verocloud/obsidian-mindmap-nextgen#50]
Add an option to allow changing the background color of a code block rendered on a mindmap diagram. Currently defaults to some very light option, which does not fit well on dark themes.

Plugin settings + front-matter + documentation.

**Comment by NickyGuants** [comment]
Hi @MasterTuto and @AdrianSimionov , I would like to work on this issue.

**Comment by AdrianSimionov** [comment]
All yours mate, @james-tindal can you please review the code and provide feedback, please, when done?

**Comment by james-tindal** [comment]
Will do @AdrianSimionov!

**Comment by NickyGuants** [comment]
Hi @AdrianSimionov, @james-tindal I have tried a bunch of different approaches for changing the background style of the code block, and none seem to be working. 

- First thing I tried is to target the code block using the id in the style property of the options when creating the mindmap.
`style: (id) => `${id} * {font: ${font}} ${id} pre code{ background-color: #f5f2f0;}`,`
- Next is creating a custom plugin like the html-escape or checkbox plugins to detect the code blocks then add a custom CSS class which I can target using a style defined in the stylesheet but this too does not work. Below is the code for the custom plugin.
`import { ITransformPlugin } from "markmap-lib";
import { wrapFunction } from "markmap-common";

export const codeBlockBgPlugin: ITransformPlugin = {
  name: "codeblockbg",
  config: {},
  transform: (transformHooks) => {
    transformHooks.afterParse.tap((md) => {
      md.parse = wrapFunction(md.parse, {
        after: (ctx) => {
          const addCodeBlockBgClass = (token: TokenWithChildren) => {
            if (token.type === "code_block") {
              // Add a custom class to the code block
              token.content = `<div class="code-block-bg">${token.content}</div>`;
            }
            if (token.children) {
              token.children = token.children.map(addCodeBlockBgClass);
            }
            return token;
          };
          ctx.result = ctx.result.map(addCodeBlockBgClass);
        },
      });
    });
    return { styles: void 0, scripts: void 0 };
  },
};`
- Can you think of anything that I might be doing wrong or any other approach that I could use?

**Comment by james-tindal** [comment]
The markmap library isn't very helpful with this. In order to allow the background colour to be updated at runtime, we need to get the svg element at this.svg, append a new style element _after_ the style element that is its first child, and update _that_ when we want to update the style.

**Comment by NickyGuants** [comment]
> The markmap library isn't very helpful with this. In order to allow the background colour to be updated at runtime, we need to get the svg element at this.svg, append a new style element _after_ the style element that is its first child, and update _that_ when we want to update the style.

Thanks, follow question though, how would we be able to target the code block element(s) in the "this.svg" to set its background color? Query Selector with "pre" and "code" tag names is not working.

**Comment by james-tindal** [comment]
You can open the chromium devtools in obsidian (cmd-shift-i on mac).
Click the "select element" icon <img width="26" alt="image" src="https://user-images.githubusercontent.com/10291002/212232059-3cb663b0-1ed1-47ce-80d6-f568ba71507e.png"> in the top left corner and select a code block on the screen.

<img width="254" alt="image" src="https://user-images.githubusercontent.com/10291002/212232965-ffbc5898-a2d5-4ea1-969d-9426c57f6db6.png">
The "styles" tab shows that the selector applying the current background-color is `.markmap-foreign code` . The indicator on the top right of that image says this style rule is coming from a `<style>` tag. If you click it, it will take you to that tag in the elements panel. It is the first child of the svg tag. 

You need to apply a selector which will have higher precedence than the currently active one. One way to do that is to use the same selector in a style tag which comes later in the page, so you can append a style tag after that one and use the same selector.

Another possibility is to edit the the current style tag:
```js
const styleEl = this.svg.firstChild
styleEl.sheet.insertRule('.markmap-foreign code: { background-color: red }')
```

**Comment by NickyGuants** [comment]
Thanks, that helps.

**Comment by NickyGuants** [comment]
Hi @AdrianSimionov , do we need to give users the option to change the text color as well?

**Comment by james-tindal** [comment]
Code with syntax highlighting has multiple colours, so that complicates things. Looks like it's got a white drop-shadow too.

**Comment by james-tindal** [comment]
Also, I notice you've changed the background colour of `.markmap-foreign`, as well as `.markmap-foreign code`.
@AdrianSimionov, is this the desired change? To demonstrate the difference:
<img width="95" alt="image" src="https://user-images.githubusercontent.com/10291002/212471400-3c0f4b78-95bf-49bc-be30-f0e420759c21.png">
We can change the background colour of only the white bit or change the red bit too.

**Comment by NickyGuants** [comment]
> Code with syntax highlighting has multiple colours, so that complicates things. Looks like it's got a white drop-shadow too.

Yes, I noticed that, which is why I was wondering how we would handle such a situation.

**Comment by NickyGuants** [comment]
> Also, I notice you've changed the background colour of `.markmap-foreign`, as well as `.markmap-foreign code`. @AdrianSimionov, is this the desired change? To demonstrate the difference: <img alt="image" width="95" src="https://user-images.githubusercontent.com/10291002/212471400-3c0f4b78-95bf-49bc-be30-f0e420759c21.png"> We can change the background colour of only the white bit or change the red bit too.

Something like this:
![image](https://user-images.githubusercontent.com/51677808/212473932-73665a9a-c988-445c-9b1b-f7766e783374.png)

**Comment by james-tindal** [comment]
Oh I see what's happening. Code blocks with different language tags have different selectors and style rules.

**Comment by james-tindal** [comment]
I think you should definitely make the `pre` background transparent.
You'll need to use this selector: `.markmap-foreign pre, .markmap-foreign pre[class*=language-]`

**Comment by NickyGuants** [comment]
> 

I am targeting that to remove the whitish outline/padding between the elements.

**Comment by NickyGuants** [comment]
@james-tindal on the issue description it says to add the front matter, I am checking the code, and I don't understand the utility of the front matter. Would you mind giving a run-through of what it does and why we need to add it?

**Comment by james-tindal** [comment]
Front-matter means a block of YAML at the beginning of a Markdown file.
This plugin allows options listed under the `markmap` key to overwrite global settings from the settings tab, on a per-document basis.
Like this:
```
---
markmap:
  codeBlockBgColor: #E76F2A
  
---

# Markdown
```

**Comment by NickyGuants** [comment]
Oh, got it.

**Comment by james-tindal** [comment]
How's it going with this, @NickyGuants ?

**Comment by james-tindal** [comment]
If we simply remove the style rule `.markmap-foreign code` from the style element inside the svg, we get this...
#### With javascript tag
<img width="328" alt="image" src="https://user-images.githubusercontent.com/10291002/216774692-4e9fa7e6-ef78-4cf4-9480-9a2cac5ce30e.png"> <img width="311" alt="image" src="https://user-images.githubusercontent.com/10291002/216774714-400904a6-8beb-4640-b44e-b1857d233f42.png">

#### With unrecognised, or no tag

<img width="710" alt="image" src="https://user-images.githubusercontent.com/10291002/216774858-dee6315b-4b49-4dc4-88b5-9c85ffc4eefb.png">
<img width="710" alt="image" src="https://user-images.githubusercontent.com/10291002/216774838-b9ad8a42-35c3-42a6-b736-11e28c2e8255.png">

@AdrianSimionov
