### ISSUE TITLE
Removing last word of a leaf when "." is used at the end

### ISSUE THREAD

**Issue by AdrianSimionov** [verocloud/obsidian-mindmap-nextgen#61]
Below code block has a very unexpected rendering:

```markmap
- root
	- Multi-region is supported, allowing you to create a key in one region and use it in a different region.
	- Multi-region is supported, allowing you to create a key in one region and use it in a different region
```
<img width="690" alt="dot bug" src="https://user-images.githubusercontent.com/6671693/210753589-eac0eccd-9cf1-4142-96ed-2f83f9e03bf2.png">

**Comment by james-tindal** [comment]
I can't replicate this on MacOS 11.6.1.
Using the latest version on branch main.
The first sentence renders fully for me.

**Comment by AdrianSimionov** [comment]
I am using MacOS Ventura 13.1, Obsidian 1.1.9, default theme and only this plugin stable version.

I tried again, still there.

**Comment by AdrianSimionov** [comment]
@NickyGuants Are you able to reproduce this issue? Can you please give it a try, assuming you are not on MacOS?

**Comment by NickyGuants** [comment]
> @NickyGuants Are you able to reproduce this issue? Can you please give it a try, assuming you are not on MacOS?

I am on windows, let me give it a try.

**Comment by NickyGuants** [comment]
Can't replicate it on windows. See the screenshot below. 

![Screenshot (18)](https://user-images.githubusercontent.com/51677808/211946219-7425bcdb-4413-4e85-8b81-88b175d96242.png)

**Comment by james-tindal** [comment]
Trying to get a Ventura virtual machine running to test this. My Mac is struggling with Big Sur so I don't want to updgrade.

**Comment by james-tindal** [comment]
I tested it on Monterrey, the version before Ventura. Didn't see the issue.
I tried to install Ventura but it broke the VM. Will try again. Maybe it needs more RAM.

**Comment by AdrianSimionov** [comment]
Seems someone else is still experiencing this bug in 1.6.0. 

Check #135

**Comment by AdrianSimionov** [comment]
I cannot reproduce anymore in version 1.6.0 the initial issue I reported here.
