### ISSUE TITLE
Copy screenshot functionality broken

### ISSUE THREAD

**Issue by AdrianSimionov** [verocloud/obsidian-mindmap-nextgen#67]
Seems that the "copy screenshot" functionality is not working in the latest stable release 1.2. Once the menu is selected, nothing is saved to clipboard.

I remember it was working in one of the branches when I previously tested.

**Comment by james-tindal** [comment]
I can't replicate this on MacOS 11.6.1.
Using the latest version on branch main.
Copy screenshot works for me.

**Comment by MasterTuto** [comment]
Could you delete or reinstall the plugin? It might be a cache problem, in the last case, may be a cached settings problem. Reinstall the plugin and retry. If it keeps not working, comment your OS version, Obsidian version, plugin version.

Also, when on obsidian, press `Ctrl + Shift + i` or `Command + Shift + I` if on MacOS and screenshot us any logging.

**Comment by AdrianSimionov** [comment]
Removing and re-installing the plugin solved the issue. I will close for now, hopefully the cache bug is not coming back.
