### ISSUE TITLE
re-design the highlight of inline markmap code

### ISSUE THREAD

**Issue by AdrianSimionov** [verocloud/obsidian-mindmap-nextgen#71]
From an UI perspective it seems a bit off.

It needs some changes, this is only a placeholder to capture ideas on how to improve the CSS of the box around the diagram.

**Comment by james-tindal** [comment]
I'm no designer but I'm thinking... Lose the glow on hover. Narrow the black border to 2 or 3 pixels.

**Comment by james-tindal** [comment]
<img width="695" alt="image" src="https://user-images.githubusercontent.com/10291002/214177470-628acc4f-a32d-4237-b83a-8a0ca3fef092.png">

So it would look like this on hover.

**Comment by AdrianSimionov** [comment]
The contrast between border and backgrounds is too low.

Maybe we can add an option to allow the user to change the border attributes?

**Comment by james-tindal** [comment]
<img width="198" alt="image" src="https://user-images.githubusercontent.com/10291002/214180990-8a839982-60f8-4fb2-a807-7c2d5f43e581.png">
To keep things simple, we could have one colour setting which would change the border and background.

**Comment by james-tindal** [comment]
Pretty much anything is achievable though.

**Comment by james-tindal** [comment]
Could drag the box to make it taller or shorter and save the result in the frontmatter.

**Comment by AdrianSimionov** [comment]
Look at how source code boxes are displayed and come with a similar approach. It would be good to use variables from the current theme, being it light or dark.
