### ISSUE TITLE
Including code block in the markdown document causes mindmap not to render.

### ISSUE THREAD

**Issue by snexus** [verocloud/obsidian-mindmap-nextgen#73]
Hi, thanks for the plugin - it looks great!

When I try to include, for example, a python code block in the original markdown, live rendering freezes, and if I try to reopen the preview - it shows a blank screen.

**Comment by AdrianSimionov** [comment]
Can you please provide the Markdown document which is reproducing the issue and confirm this plugin is the only one installed when reproducing the issue? If not, I will need to know in combination with which other plugin are you being able to reproduce the issue described above.

**Comment by AdrianSimionov** [comment]
The issue seems to be multi-line inline code rendering.

@MasterTuto Can you please tell me if this is a new feature we need to add, to render multi-line code blocks as a leaf of the mindmap, or is a bug to the existing feature where we render inline code?

**Comment by james-tindal** [comment]
I'm getting the same problem on my end. Code blocks labeled "js" or "javascript" are fine, or unrecognised words, but many programming language labels cause and error.
