### ISSUE TITLE
Allow ability to render multiple mindmaps at the same time

### ISSUE THREAD

**Issue by AdrianSimionov** [verocloud/obsidian-mindmap-nextgen#85]
Currently, we have the ability to render only one mindmap at a time, which can be pinned or not.

This feature request described the ability to have multiple rendered mindmaps at the same time.
- add a plugin generic option which changes the behavior from one rendered mindmap to multiple. when enabled, allows multiple rendered mindmaps, default value disabled.
- when multiple mindmaps feature becomes active, the "pin" functionality is always on, and the user does not have an option anymore to either pin or unpin a mindmap
- when ctrl+p mindmap option is selected, a new window is generated with a mindmap based on the active .md file
- document the behavior

Any other opinions/ideas, feel free to add here.

**Comment by james-tindal** [comment]
How about this?
A setting named "Follow active document"
### On
Only one unpinned tab.
Can have one pinned tab per document.

### Off
No pinning.
One mindmap tab per document.

**Comment by james-tindal** [comment]
Alternatively: No new setting.
Hotkey 1: Toggle map pinned to document.
Hotkey 2: Toggle map that follows the active document

**Comment by AdrianSimionov** [comment]
I am a bit confused, but assuming we call it "Render Multiple Mindmaps", default value OFF, then the following make sense to me:
ON:
No pinning.
Maps always act like they're pinned.
OFF:
Map follows the active document.
When pinned, updates only based on linked document.

New setting, definitely. Humans do not remember things, and seeing a setting is obvious. A hotkey can be implemented as an additional feature to complement the plugin settings.
